# Generated by Django 3.2.7 on 2022-06-01 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genres', models.CharField(choices=[('ЭКШН', 'ACTION'), ('ТРИЛЛЕР', 'THRILLER'), ('КОМЕДИЯ', 'COMEDY'), ('ДРАМА', 'DRAMA'), ('ФАНТАСТИКА', 'FANTASY'), ('УЖАС', 'HORROR'), ('РОМАНТИКА', 'ROMANCE')], max_length=30)),
                ('slug', models.SlugField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('country', models.CharField(choices=[('USA', 'USA'), ('FRANCE', 'FRANCE'), ('SOUTH KOREA', 'SOUTH KOREA'), ('CHINA', 'CHINA'), ('RUSSIA', 'RUSSIA'), ('ITALY', 'ITALY'), ('SPAIN', 'SPAIN'), ('JAPAN', 'JAPAN'), ('UK', 'UK')], max_length=30)),
                ('duration', models.IntegerField()),
                ('cast', models.CharField(max_length=100)),
                ('restriction', models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('14+', '14+'), ('18+', '18+'), ('21+', '21+')], max_length=30)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='images')),
                ('video', models.FileField(upload_to='videos')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='movie.genre')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movie.movie')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='movie.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'like',
                'verbose_name_plural': 'likes',
                'unique_together': {('movie', 'user')},
            },
        ),
    ]
