# Generated by Django 3.2.7 on 2022-06-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genres',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
